version: '3.8'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true


